import type { Photograph } from '../types/gallery';

export interface MemberProfile { email: string; name: string; username: string; joinedAt: string; verified: boolean; following: string[]; notifications: boolean; theme: 'dark' | 'light'; privacy: 'private' | 'public'; avatarData?: string; }
export interface MemberCollection { id: string; name: string; photoIds: string[]; isPublic: boolean; createdAt: string; }
export interface MemberData { favorites: string[]; viewed: string[]; collections: MemberCollection[]; notices: string[]; }
const PROFILE_KEY = 'aeris:profiles';
const DATA_KEY = 'aeris:member-data';
const SESSION_KEY = 'aeris:session';
const CREDENTIAL_KEY = 'aeris:credentials';
function read<T>(key: string, fallback: T): T { try { const value = localStorage.getItem(key); return value ? JSON.parse(value) as T : fallback; } catch { return fallback; } }
async function derivePassword(password: string, salt: string) { const bytes = new TextEncoder().encode(password); const key = await crypto.subtle.importKey('raw', bytes, 'PBKDF2', false, ['deriveBits']); const bits = await crypto.subtle.deriveBits({ name: 'PBKDF2', salt: Uint8Array.from(atob(salt), (c) => c.charCodeAt(0)), iterations: 120000, hash: 'SHA-256' }, key, 256); return btoa(String.fromCharCode(...new Uint8Array(bits))); }
function profiles(): Record<string, MemberProfile> { return read(PROFILE_KEY, {}); }
export function findLocalProfiles(query: string): MemberProfile[] { const needle = query.trim().toLowerCase(); return needle ? Object.values(profiles()).filter((profile) => `${profile.name} ${profile.username}`.toLowerCase().includes(needle)) : []; }
function allData(): Record<string, MemberData> { return read(DATA_KEY, {}); }
function saveData(email: string, data: MemberData) { const all = allData(); all[email] = data; localStorage.setItem(DATA_KEY, JSON.stringify(all)); window.dispatchEvent(new Event('aeris:member-change')); }
export function currentProfile(): MemberProfile | null { const email = localStorage.getItem(SESSION_KEY); return email ? profiles()[email] ?? null : null; }
export function currentEmail(): string | null { return currentProfile()?.email ?? null; }
export async function registerMember(name: string, email: string, password: string): Promise<MemberProfile> { const normalized = email.trim().toLowerCase(); const items = profiles(); if (items[normalized]) throw new Error('An account with this email already exists.'); const saltBytes = crypto.getRandomValues(new Uint8Array(16)); const salt = btoa(String.fromCharCode(...saltBytes)); const credentials = read<Record<string, { salt: string; hash: string }>>(CREDENTIAL_KEY, {}); credentials[normalized] = { salt, hash: await derivePassword(password, salt) }; localStorage.setItem(CREDENTIAL_KEY, JSON.stringify(credentials)); const profile: MemberProfile = { email: normalized, name: name.trim(), username: normalized.split('@')[0].replace(/[^a-z0-9_]/g, '') || 'observer', joinedAt: new Date().toISOString(), verified: false, following: [], notifications: true, theme: 'dark', privacy: 'private' }; items[normalized] = profile; localStorage.setItem(PROFILE_KEY, JSON.stringify(items)); localStorage.setItem(SESSION_KEY, normalized); saveData(normalized, { favorites: [], viewed: [], collections: [], notices: ['Welcome to AERIS. Your photo journal is ready.'] }); return profile; }
export async function signInMember(email: string, password: string): Promise<MemberProfile> { const normalized = email.trim().toLowerCase(); const profile = profiles()[normalized]; const credential = read<Record<string, { salt: string; hash: string }>>(CREDENTIAL_KEY, {})[normalized]; if (!profile || !credential || await derivePassword(password, credential.salt) !== credential.hash) throw new Error('Email or password is incorrect.'); localStorage.setItem(SESSION_KEY, normalized); return profile; }
export function signOutMember() { localStorage.removeItem(SESSION_KEY); }
export function createLocalResetToken(email: string): string | null { const normalized = email.trim().toLowerCase(); if (!profiles()[normalized]) return null; const token = crypto.randomUUID(); const resets = read<Record<string, { token: string; expires: number }>>('aeris:reset-tokens', {}); resets[normalized] = { token, expires: Date.now() + 15 * 60_000 }; localStorage.setItem('aeris:reset-tokens', JSON.stringify(resets)); return token; }
export async function completeLocalPasswordReset(email: string, token: string, password: string): Promise<void> { const normalized = email.trim().toLowerCase(); const resets = read<Record<string, { token: string; expires: number }>>('aeris:reset-tokens', {}); const record = resets[normalized]; if (!record || record.expires < Date.now() || record.token !== token) throw new Error('That reset token is invalid or expired. Request a new one.'); const credentials = read<Record<string, { salt: string; hash: string }>>(CREDENTIAL_KEY, {}); const saltBytes = crypto.getRandomValues(new Uint8Array(16)); const salt = btoa(String.fromCharCode(...saltBytes)); credentials[normalized] = { salt, hash: await derivePassword(password, salt) }; localStorage.setItem(CREDENTIAL_KEY, JSON.stringify(credentials)); delete resets[normalized]; localStorage.setItem('aeris:reset-tokens', JSON.stringify(resets)); }
export function updateProfile(patch: Partial<Pick<MemberProfile, 'name'|'notifications'|'theme'|'verified'|'following'|'privacy'|'avatarData'>>): MemberProfile | null { const profile = currentProfile(); if (!profile) return null; const items = profiles(); items[profile.email] = { ...profile, ...patch }; localStorage.setItem(PROFILE_KEY, JSON.stringify(items)); window.dispatchEvent(new Event('aeris:member-change')); return items[profile.email]; }
export function memberData(email = currentEmail()): MemberData { return email ? allData()[email] ?? { favorites: [], viewed: [], collections: [], notices: [] } : { favorites: [], viewed: [], collections: [], notices: [] }; }
export function toggleFavorite(id: string): boolean { const email = currentEmail(); if (!email) { window.location.assign('/login?next=favorites'); return false; } const data = memberData(email); const wasSaved = data.favorites.includes(id); saveData(email, { ...data, favorites: wasSaved ? data.favorites.filter((item) => item !== id) : [...data.favorites, id] }); return !wasSaved; }
export function isFavorite(id: string): boolean { return memberData().favorites.includes(id); }
export function recordView(photo: Photograph) { const email = currentEmail(); if (!email) return; const data = memberData(email); saveData(email, { ...data, viewed: [photo.id, ...data.viewed.filter((item) => item !== photo.id)].slice(0, 30) }); }
export function addCollection(name: string): void { const email = currentEmail(); if (!email) return; const data = memberData(email); saveData(email, { ...data, collections: [...data.collections, { id: crypto.randomUUID(), name: name.trim(), photoIds: [], isPublic: false, createdAt: new Date().toISOString() }] }); }
export function updateCollection(id: string, patch: Partial<Pick<MemberCollection, 'name'|'photoIds'|'isPublic'>>) { const email = currentEmail(); if (!email) return; const data = memberData(email); saveData(email, { ...data, collections: data.collections.map((collection) => collection.id === id ? { ...collection, ...patch } : collection) }); }
export function deleteCollection(id: string) { const email = currentEmail(); if (!email) return; const data = memberData(email); saveData(email, { ...data, collections: data.collections.filter((collection) => collection.id !== id) }); }
export function addNotice(message: string) { const email = currentEmail(); if (!email) return; const data = memberData(email); saveData(email, { ...data, notices: [message, ...data.notices].slice(0, 20) }); }
