import type { Photograph } from '../types/gallery';
import { isSupabaseConfigured, supabase } from './supabaseClient';

export interface MemberProfile { email: string; name: string; username: string; joinedAt: string; verified: boolean; following: string[]; notifications: boolean; theme: 'dark' | 'light'; privacy: 'private' | 'public'; avatarData?: string; }
export interface MemberCollection { id: string; name: string; photoIds: string[]; isPublic: boolean; createdAt: string; }
export interface MemberData { favorites: string[]; viewed: string[]; collections: MemberCollection[]; notices: string[]; }
const PROFILE_KEY = 'aeris:profiles';
const DATA_KEY = 'aeris:member-data';
const SESSION_KEY = 'aeris:session';
const CREDENTIAL_KEY = 'aeris:credentials';
function read<T>(key: string, fallback: T): T { try { const value = localStorage.getItem(key); return value ? JSON.parse(value) as T : fallback; } catch { return fallback; } }
async function derivePassword(password: string, salt: string) { const bytes = new TextEncoder().encode(password); const key = await crypto.subtle.importKey('raw', bytes, 'PBKDF2', false, ['deriveBits']); const bits = await crypto.subtle.deriveBits({ name: 'PBKDF2', salt: Uint8Array.from(atob(salt), (c) => c.charCodeAt(0)), iterations: 120000, hash: 'SHA-256' }, key, 256); return btoa(String.fromCharCode(...new Uint8Array(bits))); }
function profiles(): Record<string, MemberProfile> { return read(PROFILE_KEY, {}); }
export function findLocalProfiles(query: string): MemberProfile[] { const needle = query.trim().toLowerCase(); return needle ? Object.values(profiles()).filter((profile) => `${profile.name} ${profile.username}`.toLowerCase().includes(needle)) : []; }
export function findLocalProfileByUsername(username: string): MemberProfile | null { return Object.values(profiles()).find((profile) => profile.username === username) ?? null; }
export function localFollowerCount(username: string): number { return Object.values(profiles()).filter((profile) => profile.following.includes(username)).length; }
function allData(): Record<string, MemberData> { return read(DATA_KEY, {}); }
function saveData(email: string, data: MemberData) { const all = allData(); all[email] = data; localStorage.setItem(DATA_KEY, JSON.stringify(all)); window.dispatchEvent(new Event('aeris:member-change')); }
function syncCloud(write: (userId: string) => PromiseLike<{ error: { message: string } | null }>) { if (!isSupabaseConfigured || !supabase) return; void supabase.auth.getUser().then(({ data, error }) => { if (error) throw error; if (!data.user) throw new Error('Your AERIS session has expired.'); return write(data.user.id); }).then((result) => { if (result?.error) throw result.error; }).catch((error: unknown) => window.dispatchEvent(new CustomEvent('aeris:sync-error', { detail: error instanceof Error ? error.message : 'AERIS could not sync this change.' }))); }
export function currentProfile(): MemberProfile | null { if (isSupabaseConfigured) return read<MemberProfile | null>('aeris:supabase-profile-cache', null); const email = localStorage.getItem(SESSION_KEY); return email ? profiles()[email] ?? null : null; }
export function currentEmail(): string | null { return isSupabaseConfigured ? read<MemberProfile | null>('aeris:supabase-profile-cache', null)?.email ?? null : localStorage.getItem(SESSION_KEY); }
export async function registerMember(name: string, email: string, password: string): Promise<MemberProfile> { const normalized = email.trim().toLowerCase(); const items = profiles(); if (items[normalized]) throw new Error('An account with this email already exists.'); const saltBytes = crypto.getRandomValues(new Uint8Array(16)); const salt = btoa(String.fromCharCode(...saltBytes)); const credentials = read<Record<string, { salt: string; hash: string }>>(CREDENTIAL_KEY, {}); credentials[normalized] = { salt, hash: await derivePassword(password, salt) }; localStorage.setItem(CREDENTIAL_KEY, JSON.stringify(credentials)); const profile: MemberProfile = { email: normalized, name: name.trim(), username: normalized.split('@')[0].replace(/[^a-z0-9_]/g, '') || 'observer', joinedAt: new Date().toISOString(), verified: false, following: [], notifications: true, theme: 'dark', privacy: 'private' }; items[normalized] = profile; localStorage.setItem(PROFILE_KEY, JSON.stringify(items)); localStorage.setItem(SESSION_KEY, normalized); saveData(normalized, { favorites: [], viewed: [], collections: [], notices: ['Welcome to AERIS. Your photo journal is ready.'] }); return profile; }
export async function signInMember(email: string, password: string): Promise<MemberProfile> { const normalized = email.trim().toLowerCase(); const profile = profiles()[normalized]; const credential = read<Record<string, { salt: string; hash: string }>>(CREDENTIAL_KEY, {})[normalized]; if (!profile || !credential || await derivePassword(password, credential.salt) !== credential.hash) throw new Error('Email or password is incorrect.'); localStorage.setItem(SESSION_KEY, normalized); return profile; }
export function signOutMember() { localStorage.removeItem(SESSION_KEY); }
export function createLocalResetToken(email: string): string | null { const normalized = email.trim().toLowerCase(); if (!profiles()[normalized]) return null; const token = crypto.randomUUID(); const resets = read<Record<string, { token: string; expires: number }>>('aeris:reset-tokens', {}); resets[normalized] = { token, expires: Date.now() + 15 * 60_000 }; localStorage.setItem('aeris:reset-tokens', JSON.stringify(resets)); return token; }
export async function completeLocalPasswordReset(email: string, token: string, password: string): Promise<void> { const normalized = email.trim().toLowerCase(); const resets = read<Record<string, { token: string; expires: number }>>('aeris:reset-tokens', {}); const record = resets[normalized]; if (!record || record.expires < Date.now() || record.token !== token) throw new Error('That reset token is invalid or expired. Request a new one.'); const credentials = read<Record<string, { salt: string; hash: string }>>(CREDENTIAL_KEY, {}); const saltBytes = crypto.getRandomValues(new Uint8Array(16)); const salt = btoa(String.fromCharCode(...saltBytes)); credentials[normalized] = { salt, hash: await derivePassword(password, salt) }; localStorage.setItem(CREDENTIAL_KEY, JSON.stringify(credentials)); delete resets[normalized]; localStorage.setItem('aeris:reset-tokens', JSON.stringify(resets)); }
export function updateProfile(patch: Partial<Pick<MemberProfile, 'name'|'notifications'|'theme'|'verified'|'following'|'privacy'|'avatarData'>>): MemberProfile | null { const profile = currentProfile(); if (!profile) return null; const updated = { ...profile, ...patch }; if (isSupabaseConfigured) { localStorage.setItem('aeris:supabase-profile-cache', JSON.stringify(updated)); syncCloud((userId) => supabase!.from('profiles').update({ display_name: patch.name, notifications_enabled: patch.notifications, theme: patch.theme, is_public: patch.privacy === undefined ? undefined : patch.privacy === 'public' }).eq('id', userId)); } else { const items = profiles(); items[profile.email] = updated; localStorage.setItem(PROFILE_KEY, JSON.stringify(items)); } window.dispatchEvent(new Event('aeris:member-change')); return updated; }
export function memberData(email = currentEmail()): MemberData { return email ? allData()[email] ?? { favorites: [], viewed: [], collections: [], notices: [] } : { favorites: [], viewed: [], collections: [], notices: [] }; }
export function replaceMemberData(email: string, data: MemberData) { saveData(email, data); }
export function toggleFavorite(id: string): boolean { const email = currentEmail(); if (!email) { window.location.assign('/login?next=favorites'); return false; } const data = memberData(email); const wasSaved = data.favorites.includes(id); saveData(email, { ...data, favorites: wasSaved ? data.favorites.filter((item) => item !== id) : [...data.favorites, id] }); syncCloud((userId) => wasSaved ? supabase!.from('favorites').delete().eq('user_id', userId).eq('photo_id', id) : supabase!.from('favorites').insert({ user_id: userId, photo_id: id })); return !wasSaved; }
export function isFavorite(id: string): boolean { return memberData().favorites.includes(id); }
export function recordView(photo: Photograph) { const email = currentEmail(); if (!email) return; const data = memberData(email); saveData(email, { ...data, viewed: [photo.id, ...data.viewed.filter((item) => item !== photo.id)].slice(0, 30) }); syncCloud((userId) => supabase!.from('view_history').insert({ user_id: userId, photo_id: photo.id })); }
export function addCollection(name: string): void { const email = currentEmail(); if (!email) return; const data = memberData(email); const collection = { id: crypto.randomUUID(), name: name.trim(), photoIds: [], isPublic: false, createdAt: new Date().toISOString() }; saveData(email, { ...data, collections: [...data.collections, collection] }); syncCloud((userId) => supabase!.from('collections').insert({ id: collection.id, user_id: userId, title: collection.name, is_public: collection.isPublic })); }
export function updateCollection(id: string, patch: Partial<Pick<MemberCollection, 'name'|'photoIds'|'isPublic'>>) { const email = currentEmail(); if (!email) return; const data = memberData(email); saveData(email, { ...data, collections: data.collections.map((collection) => collection.id === id ? { ...collection, ...patch } : collection) }); syncCloud(async (userId) => { if (patch.name !== undefined || patch.isPublic !== undefined) { const { error } = await supabase!.from('collections').update({ title: patch.name, is_public: patch.isPublic }).eq('id', id).eq('user_id', userId); if (error) return { error }; } if (patch.photoIds !== undefined) { const { error: removeError } = await supabase!.from('collection_photos').delete().eq('collection_id', id); if (removeError) return { error: removeError }; if (patch.photoIds.length) return supabase!.from('collection_photos').insert(patch.photoIds.map((photoId) => ({ collection_id: id, photo_id: photoId }))); } return { error: null }; }); }
export function deleteCollection(id: string) { const email = currentEmail(); if (!email) return; const data = memberData(email); saveData(email, { ...data, collections: data.collections.filter((collection) => collection.id !== id) }); syncCloud((userId) => supabase!.from('collections').delete().eq('id', id).eq('user_id', userId)); }
export function addNotice(message: string) { const email = currentEmail(); if (!email) return; const data = memberData(email); saveData(email, { ...data, notices: [message, ...data.notices].slice(0, 20) }); }
