import { useEffect, useMemo, useState } from 'react';
import type { FormEvent, ReactNode } from 'react';
import { ArrowLeft, Bell, Heart, LogOut, Plus, Search, Trash2, UserRound } from 'lucide-react';
import { photographs, imageUrl } from '../data/gallery';
import { addCollection, addNotice, completeLocalPasswordReset, createLocalResetToken, currentProfile, deleteCollection, findLocalProfiles, isFavorite, memberData, registerMember, signInMember, signOutMember, toggleFavorite, updateCollection, updateProfile, type MemberProfile } from '../services/memberStore';
import type { Photograph } from '../types/gallery';
import './member.css';

function navigate(path: string) { history.pushState({}, '', path); window.dispatchEvent(new PopStateEvent('popstate')); window.scrollTo(0, 0); }
function Link({ to, children }: { to: string; children: ReactNode }) { return <a href={to} onClick={(event) => { event.preventDefault(); navigate(to); }}>{children}</a>; }
function routeNow() { return `${location.pathname}${location.search}`; }
function goAfterAuth() { const next = new URLSearchParams(location.search).get('next'); navigate(next === 'favorites' ? '/favorites' : '/dashboard'); }
function Protected({ profile, children }: { profile: MemberProfile | null; children: ReactNode }) { useEffect(() => { if (!profile) navigate(`/login?next=${encodeURIComponent(location.pathname.slice(1) || 'dashboard')}`); }, [profile]); return profile ? <>{children}</> : null; }
function PhotoTile({ photo, action, query = '' }: { photo: Photograph; action?: React.ReactNode; query?: string }) { return <article className="member-photo"><img src={imageUrl(photo.image, 700)} loading="lazy" alt={photo.description ?? photo.title} /><div><small><Highlight text={`${photo.category} · ${photo.location}`} query={query}/></small><strong><Highlight text={photo.title} query={query}/></strong>{action}</div></article>; }
function Highlight({ text, query }: { text: string; query: string }) { if (!query.trim()) return <>{text}</>; const parts = text.split(new RegExp(`(${query.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')})`, 'ig')); return <>{parts.map((part, index) => part.toLowerCase() === query.toLowerCase() ? <mark key={`${part}-${index}`}>{part}</mark> : part)}</>; }

export function MemberExperience({ children }: { children: ReactNode }) {
  const [route, setRoute] = useState(routeNow);
  const [profile, setProfile] = useState(currentProfile);
  const [revision, setRevision] = useState(0);
  useEffect(() => { const onPop = () => { setRoute(routeNow()); setProfile(currentProfile()); }; const onChange = () => { setProfile(currentProfile()); setRevision((v) => v + 1); }; window.addEventListener('popstate', onPop); window.addEventListener('aeris:member-change', onChange); window.addEventListener('storage', onChange); return () => { window.removeEventListener('popstate', onPop); window.removeEventListener('aeris:member-change', onChange); window.removeEventListener('storage', onChange); }; }, []);
  const data = memberData();
  const authPath = ['/login','/register','/forgot-password','/verify-email','/reset-password'].includes(location.pathname);
  if (location.pathname === '/' && !authPath) return <>{children}<aside className="account-launch"><Link to={profile ? '/dashboard' : '/login'}>{profile ? profile.name : 'Member sign in'} <UserRound size={15}/></Link></aside></>;
  const logout = () => { signOutMember(); setProfile(null); navigate('/'); };
  return <div className="member-shell" data-theme={profile?.theme ?? 'dark'} data-member-revision={revision}><header className="member-top"><Link to="/"><ArrowLeft size={15}/> Back to AERIS</Link><Link to="/"><span>A E R I S</span><small>Moments Above.</small></Link><nav><Link to="/dashboard">Journal</Link><Link to="/favorites">Favorites</Link><Link to="/collections">Collections</Link><Link to="/search">Search</Link><Link to="/contact">Contact</Link>{profile && <button onClick={logout} aria-label="Sign out"><LogOut size={16}/></button>}</nav></header>
    {authPath ? <AuthScreen path={location.pathname} onSuccess={() => { setProfile(currentProfile()); goAfterAuth(); }} /> : location.pathname === '/contact' || location.pathname.startsWith('/profile/') || location.pathname === '/search' ? <MemberPage route={route} profile={profile ?? { email: '', name: 'Guest', username: 'guest', joinedAt: new Date().toISOString(), verified: false, following: [], notifications: false, theme: 'dark', privacy: 'private' }} data={data} refresh={() => setRevision((v) => v + 1)} /> : <Protected profile={profile}><MemberPage route={route} profile={profile!} data={data} refresh={() => setRevision((v) => v + 1)} /></Protected>}
  </div>;
}

function AuthScreen({ path, onSuccess }: { path: string; onSuccess: () => void }) {
  const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(''); setMessage(''); const form = new FormData(event.currentTarget); const email = String(form.get('email') ?? ''); setBusy(true); try {
    if (path === '/register') { const name = String(form.get('name') ?? ''); const password = String(form.get('password') ?? ''); if (password.length < 8) throw new Error('Use at least 8 characters for your password.'); await registerMember(name, email, password); onSuccess(); }
    else if (path === '/login') { await signInMember(email, String(form.get('password') ?? '')); onSuccess(); }
    else if (path === '/forgot-password') { const token = createLocalResetToken(email); if (!token) throw new Error('No local account found for this email.'); setMessage(`Local reset token (valid 15 minutes): ${token}`); }
    else if (path === '/verify-email') { if (!updateProfile({ verified: true })) throw new Error('Sign in or create an account before verifying your email.'); setMessage('Email marked as verified for this local demo.'); }
    else if (path === '/reset-password') { const password = String(form.get('password') ?? ''); if (password.length < 8) throw new Error('Use at least 8 characters for your password.'); await completeLocalPasswordReset(email, String(form.get('token') ?? ''), password); setMessage('Password updated. You can now sign in.'); }
  } catch (e) { setError(e instanceof Error ? e.message : 'Something went wrong.'); } finally { setBusy(false); } };
  const title = path === '/register' ? 'Create your journal' : path === '/forgot-password' ? 'Find your way back' : path === '/verify-email' ? 'Verify your email' : path === '/reset-password' ? 'Choose a new password' : 'Welcome back';
  return <main className="auth-stage"><section className="auth-card"><p className="eyebrow">A private place for what moves you</p><h1>{title}</h1><p>Keep the moments that make you look up.</p><form onSubmit={submit}>{path === '/register' && <label>Your name<input name="name" autoComplete="name" required/></label>}{path !== '/verify-email' && <label>Email address<input name="email" type="email" autoComplete="email" required/></label>}{path === '/reset-password' && <label>Reset token<input name="token" required/></label>}{(path === '/register' || path === '/login' || path === '/reset-password') && <label>Password<input name="password" type="password" autoComplete={path === '/login' ? 'current-password' : 'new-password'} minLength={8} required/></label>}<button className="member-primary" type="submit" disabled={busy}>{busy ? 'Please wait…' : path === '/register' ? 'Create account' : path === '/login' ? 'Sign in' : path === '/forgot-password' ? 'Create reset token' : path === '/verify-email' ? 'Verify email' : 'Reset password'}</button></form>{error && <p className="member-error" role="alert">{error}</p>}{message && <p className="member-success" role="status">{message}</p>}<div className="auth-links">{path !== '/login' && <Link to="/login">Sign in</Link>}{path !== '/register' && <Link to="/register">Create account</Link>}{path === '/login' && <Link to="/forgot-password">Forgot password?</Link>}{path === '/forgot-password' && <Link to="/reset-password">Enter a reset token</Link>}{path === '/register' && <Link to="/verify-email">Verify email</Link>}</div><small className="demo-note">Local demo: profiles, password hashes, and saved items live only in this browser. Reset tokens are shown on screen; email verification and message delivery need a connected provider.</small></section></main>;
}

function MemberPage({ route, profile, data, refresh }: { route: string; profile: MemberProfile; data: ReturnType<typeof memberData>; refresh: () => void }) {
  const [query, setQuery] = useState(''); const [debouncedQuery, setDebouncedQuery] = useState(''); const [notice, setNotice] = useState('');
  useEffect(() => { const timer = window.setTimeout(() => setDebouncedQuery(query), 180); return () => window.clearTimeout(timer); }, [query]);
  const photos = useMemo(() => photographs.filter((photo) => data.favorites.includes(photo.id)), [data.favorites]);
  const searchResults = useMemo(() => { const q = debouncedQuery.trim().toLowerCase(); return q ? photographs.filter((photo) => `${photo.title} ${photo.category} ${photo.location} ${photo.description}`.toLowerCase().includes(q)) : []; }, [debouncedQuery]);
  const collectionResults = useMemo(() => { const q = debouncedQuery.trim().toLowerCase(); return q ? data.collections.filter((collection) => collection.name.toLowerCase().includes(q)) : []; }, [data.collections, debouncedQuery]);
  const userResults = useMemo(() => findLocalProfiles(debouncedQuery), [debouncedQuery]);
  const section = route.split('?')[0];
  const toggle = (photo: Photograph) => { toggleFavorite(photo.id); refresh(); };
  const create = () => { const name = prompt('Name this collection'); if (name?.trim()) { addCollection(name); addNotice(`Collection created: ${name.trim()}`); refresh(); } };
  const profileLabel = section === '/profile/me' ? profile.name : section.startsWith('/profile/') ? `@${decodeURIComponent(section.slice('/profile/'.length))}` : profile.name;
  const title = section === '/favorites' ? 'Saved photographs' : section === '/collections' ? 'Your collections' : section === '/search' ? 'Find a moment' : section === '/contact' ? 'Start a conversation' : section === '/notifications' ? 'Notifications' : section.startsWith('/profile/') ? profileLabel : 'Your journal';
  return <main className="member-content"><p className="eyebrow">AERIS / MEMBER JOURNAL</p><h1>{title}</h1>
    {section === '/dashboard' && <><div className="member-grid"><section className="member-panel"><div className="member-avatar" aria-label={`${profile.name} profile image`}>{profile.name.slice(0,1).toUpperCase()}</div><h2>{profile.name}</h2><p>{profile.email}</p><small>Member since {new Date(profile.joinedAt).toLocaleDateString()}</small><Link to="/profile/me">View profile</Link></section><section className="member-panel"><Heart/><h2>Your activity</h2><p>{data.viewed.length} photos viewed · {data.collections.length} collections · {data.favorites.length} favorites</p><Link to="/favorites">Explore your saved photographs →</Link></section><section className="member-panel"><Bell/><h2>Notifications</h2><Link to="/notifications">View notification center →</Link><label className="member-check"><input type="checkbox" checked={profile.notifications} onChange={(e) => { updateProfile({ notifications: e.target.checked }); refresh(); }}/> Receive journal updates</label>{data.notices.slice(0,2).map((item) => <p key={item}>{item}</p>)}</section><section className="member-panel"><h2>Preferences</h2><label>Theme <select value={profile.theme} onChange={(e) => { updateProfile({ theme: e.target.value as 'dark'|'light' }); refresh(); }}><option value="dark">Dark</option><option value="light">Light</option></select></label><label>Profile visibility <select value={profile.privacy} onChange={(e) => { updateProfile({ privacy: e.target.value as 'private'|'public' }); refresh(); }}><option value="private">Private</option><option value="public">Public</option></select></label></section></div><div className="member-toolbar"><h2>Recently viewed</h2><Link to="/search">Discover more →</Link></div><div className="member-gallery">{data.viewed.map((id) => { const photo = photographs.find((p) => p.id === id); return photo ? <PhotoTile key={id} photo={photo}/> : null; })}</div><div className="member-toolbar"><h2>Recommended for you</h2><Link to="/favorites">Based on your saved moments →</Link></div><div className="member-gallery">{photographs.filter((photo) => !data.favorites.includes(photo.id) && (!data.favorites.length || photographs.find((item) => item.id === data.favorites[0])?.category === photo.category)).slice(0,3).map((photo) => <PhotoTile key={photo.id} photo={photo} action={<button onClick={() => toggle(photo)}><Heart size={15}/> Save</button>}/>)}</div></>}
    {section === '/favorites' && <><p className="member-lede">{photos.length} photographs held close.</p>{photos.length ? <div className="member-gallery">{photos.map((photo) => <PhotoTile key={photo.id} photo={photo} action={<button onClick={() => toggle(photo)} aria-label={`Remove ${photo.title} from favorites`}><Heart fill="currentColor" size={16}/> Saved</button>}/>)}</div> : <div className="member-empty"><Heart/><h2>A little space for what you love.</h2><p>Save a photograph from the gallery and it will be waiting here.</p><Link to="/#collection">Visit the collection →</Link></div>}</>}
    {section === '/collections' && <><div className="member-toolbar"><p className="member-lede">Personal albums, gathered in one place.</p><button className="member-primary" onClick={create}><Plus size={16}/> New collection</button></div>{data.collections.length ? <div className="member-grid">{data.collections.map((collection) => <section className="member-panel" key={collection.id}><h2>{collection.name}</h2><p>{collection.photoIds.length} photographs · {collection.isPublic ? 'Public' : 'Private'}</p><button className="member-delete" onClick={() => { const name = prompt('Rename collection', collection.name); if (name?.trim()) { updateCollection(collection.id, { name: name.trim() }); refresh(); } }}>Rename collection</button><label>Add a saved photograph <select defaultValue="" onChange={(e) => { if (!e.target.value) return; updateCollection(collection.id, { photoIds: [...new Set([...collection.photoIds, e.target.value])] }); refresh(); }}><option value="">Choose photo</option>{photos.map((photo) => <option key={photo.id} value={photo.id}>{photo.title}</option>)}</select></label><ul>{collection.photoIds.map((id) => <li key={id}>{photographs.find((p) => p.id === id)?.title ?? id} <button onClick={() => { updateCollection(collection.id, { photoIds: collection.photoIds.filter((item) => item !== id) }); refresh(); }}>Remove</button></li>)}</ul><label><input type="checkbox" checked={collection.isPublic} onChange={(e) => { updateCollection(collection.id, { isPublic: e.target.checked }); refresh(); }}/> Make public</label><button className="member-delete" onClick={() => { deleteCollection(collection.id); refresh(); }}><Trash2 size={14}/> Delete collection</button></section>)}</div> : <div className="member-empty"><h2>Give your photographs a place.</h2><button className="member-primary" onClick={create}>Create your first collection</button></div>}</>}
    {section === '/search' && <><label className="member-search"><Search/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Try ‘clouds’, ‘Norway’ or ‘first light’" autoFocus/></label>{collectionResults.length > 0 && <div className="member-search-collections"><h2>Collections</h2>{collectionResults.map((collection) => <Link key={collection.id} to="/collections"><Highlight text={collection.name} query={debouncedQuery}/> <small>{collection.photoIds.length} photographs</small></Link>)}</div>}{userResults.length > 0 && <div className="member-search-collections"><h2>Photographers</h2>{userResults.map((user) => <Link key={user.email} to={`/profile/${user.username}`}><Highlight text={user.name} query={debouncedQuery}/> <small>@{user.username}</small></Link>)}</div>}<div className="member-gallery">{searchResults.map((photo) => <PhotoTile key={photo.id} photo={photo} query={debouncedQuery} action={<button onClick={() => toggle(photo)} aria-pressed={isFavorite(photo.id)}><Heart size={16} fill={isFavorite(photo.id) ? 'currentColor' : 'none'}/> {isFavorite(photo.id) ? 'Saved' : 'Save'}</button>}/>)}</div>{query && searchResults.length === 0 && collectionResults.length === 0 && userResults.length === 0 && <p className="member-empty">No photographs, collections, or people found. Try a category or location.</p>}</>}
    {section.startsWith('/profile/') && <div className="member-panel"><UserRound/><h2>{profileLabel}</h2><p>{profile.name} · {profile.email || 'Public AERIS profile'}</p><button className="member-primary" onClick={() => { const following = profile.following.includes('aeris-studio') ? profile.following.filter((x) => x !== 'aeris-studio') : [...profile.following, 'aeris-studio']; updateProfile({ following }); addNotice(following.includes('aeris-studio') ? 'You are following AERIS Studio.' : 'You unfollowed AERIS Studio.'); refresh(); }}>{profile.following.includes('aeris-studio') ? 'Following AERIS Studio' : 'Follow AERIS Studio'}</button><p>{data.collections.filter((c) => c.isPublic).length} public collections</p></div>}
    {section === '/contact' && <form className="member-panel contact-form" onSubmit={(e) => { e.preventDefault(); setNotice('Your inquiry is saved in this local demo. Connect an email service to deliver it.'); }}><h2>Let’s make something meaningful.</h2><label>Your name<input required/></label><label>Email<input type="email" required/></label><label>Inquiry type<select><option>Photography commission</option><option>Collaboration</option><option>Print licensing</option></select></label><label>How can we help?<textarea required rows={5}/></label><button className="member-primary">Send inquiry</button>{notice && <p role="status">{notice}</p>}</form>}
    {section === '/notifications' && <div className="member-panel"><h2>Your notification center</h2>{data.notices.length ? data.notices.map((item, index) => <p key={`${item}-${index}`}>{item}</p>) : <p>Your journal is quiet for now.</p>}</div>}
    <footer className="member-foot"><Link to="/contact">Inquiries</Link><span>Crafted for moments above.</span><Link to="/dashboard">Privacy & settings</Link></footer>
  </main>;
}
