import { lazy, Suspense, useEffect, useMemo, useState } from 'react';
import type { FormEvent, ReactNode } from 'react';
import { ArrowLeft, Bell, Heart, LogOut, Plus, Search, Trash2, UserRound } from 'lucide-react';
import { photographs, imageUrl } from '../data/gallery';
import { handleSkyImageFallback } from './imageFallback';
import { galleryFacets } from '../data/galleryFacets';
import { addCollection, addNotice, currentProfile, deleteCollection, findLocalProfileByUsername, findLocalProfiles, isFavorite, localFollowerCount, memberData, registerMember, replaceMemberData, signInMember, signOutMember, toggleFavorite, updateCollection, updateProfile, type MemberProfile } from '../services/memberStore';
import { cachedSupabaseProfile, loadSupabaseMemberData, loadSupabaseProfile, requestSupabasePasswordReset, signInWithSupabase, signOutSupabase, signUpWithSupabase, updateSupabasePassword } from '../services/supabaseMemberService';
import { isSupabaseConfigured, supabase } from '../services/supabaseClient';
import type { Photograph } from '../types/gallery';
import { ContactForm } from './ContactForm';
import './member.css';

const CloudAtlasPage = lazy(() => import('../features/cloud-atlas/CloudAtlasPage').then((module) => ({ default: module.CloudAtlasPage })));
const PlannerPage = lazy(() => import('../features/planner/PlannerPage').then((module) => ({ default: module.PlannerPage })));
const PhotoDetailPage = lazy(() => import('../features/photograph/PhotoDetailPage').then((module) => ({ default: module.PhotoDetailPage })));
const InquiryInbox = lazy(() => import('../features/admin/InquiryInbox').then((module) => ({ default: module.InquiryInbox })));
const OnboardingPage = lazy(() => import('../features/onboarding/OnboardingPage').then((module) => ({ default: module.OnboardingPage })));

function navigate(path: string) { history.pushState({}, '', path); window.dispatchEvent(new PopStateEvent('popstate')); window.scrollTo(0, 0); }
function Link({ to, children }: { to: string; children: ReactNode; }) { const active=location.pathname===to; return <a href={to} aria-current={active?'page':undefined} onClick={(event) => { event.preventDefault(); navigate(to); }}>{children}</a>; }
function routeNow() { return `${location.pathname}${location.search}`; }
function goAfterAuth() { const next=new URLSearchParams(location.search).get('next'); const allowed=['/favorites', '/dashboard', '/collections', '/search', '/notifications']; navigate(next&&(allowed.includes(next)||next.startsWith('/profile/')||next.startsWith('/admin/'))? next:'/dashboard'); }
function Protected({ profile, ready, children }: { profile: MemberProfile|null; ready: boolean; children: ReactNode; }) { useEffect(() => { if (ready&&!profile) navigate(`/login?next=${encodeURIComponent(location.pathname.slice(1)||'dashboard')}`); }, [profile, ready]); return ready&&profile? <>{children}</>:<main id="main-content" className="member-content" role="status" aria-live="polite">Loading your AERIS journal…</main>; }
function PhotoTile({ photo, action, query='' }: { photo: Photograph; action?: React.ReactNode; query?: string; }) { return <article className="member-photo"><img src={imageUrl(photo.image, 700)} width="1600" height="1200" loading="lazy" alt={photo.description??photo.title} onError={handleSkyImageFallback} /><div><small><Highlight text={`${photo.category} · ${photo.location}`} query={query} /></small><strong><Highlight text={photo.title} query={query} /></strong>{action}</div></article>; }
function Highlight({ text, query }: { text: string; query: string; }) { if (!query.trim()) return <>{text}</>; const parts=text.split(new RegExp(`(${query.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')})`, 'ig')); return <>{parts.map((part, index) => part.toLowerCase()===query.toLowerCase()? <mark key={`${part}-${index}`}>{part}</mark>:part)}</>; }

export function MemberExperience({ children }: { children: ReactNode; }) {
  const [route, setRoute]=useState(routeNow);
  const [profile, setProfile]=useState(() => isSupabaseConfigured? cachedSupabaseProfile():currentProfile());
  const [authReady, setAuthReady]=useState(!isSupabaseConfigured);
  const [revision, setRevision]=useState(0);
  const [syncError, setSyncError]=useState('');
  useEffect(() => {
    if (!isSupabaseConfigured||!supabase) return;
    let mounted=true;
    const refreshProfile=() => { void (async () => { const nextProfile=await loadSupabaseProfile(); if (nextProfile) { try { const cloudData=await loadSupabaseMemberData(); if (cloudData) replaceMemberData(cloudData.email, cloudData.data); } catch (error) { window.dispatchEvent(new CustomEvent('aeris:sync-error', { detail: error instanceof Error? error.message:'Could not load member data.' })); } } if (mounted) { setProfile(nextProfile); setAuthReady(true); } })().catch(() => { if (mounted) { setProfile(null); setAuthReady(true); } }); };
    refreshProfile();
    const { data: { subscription } }=supabase.auth.onAuthStateChange((_event, session) => {
      if (!session) { setProfile(null); setAuthReady(true); }
      else { setAuthReady(false); window.setTimeout(refreshProfile, 0); }
    });
    const onCloudAuth=(event: Event) => { const custom=event as CustomEvent<MemberProfile|null>; setProfile(custom.detail); setAuthReady(true); };
    window.addEventListener('aeris:cloud-auth', onCloudAuth);
    return () => { mounted=false; subscription.unsubscribe(); window.removeEventListener('aeris:cloud-auth', onCloudAuth); };
  }, []);
  useEffect(() => { const onPop=() => { setRoute(routeNow()); setProfile(currentProfile()); }; const onChange=() => { if (!isSupabaseConfigured) setProfile(currentProfile()); setRevision((v) => v+1); }; const onSyncError=(event: Event) => setSyncError((event as CustomEvent<string>).detail); window.addEventListener('popstate', onPop); window.addEventListener('aeris:member-change', onChange); window.addEventListener('storage', onChange); window.addEventListener('aeris:sync-error', onSyncError); return () => { window.removeEventListener('popstate', onPop); window.removeEventListener('aeris:member-change', onChange); window.removeEventListener('storage', onChange); window.removeEventListener('aeris:sync-error', onSyncError); }; }, []);
  useEffect(() => {
    if (location.pathname === '/') return;
    window.scrollTo(0, 0);
    const frame = window.requestAnimationFrame(() => {
      const heading = document.querySelector<HTMLElement>('#main-content h1');
      if (heading) { heading.tabIndex = -1; heading.focus({ preventScroll: true }); }
    });
    return () => window.cancelAnimationFrame(frame);
  }, [route, authReady]);
  const data=memberData();
  const authPath=['/login', '/register', '/forgot-password', '/verify-email', '/reset-password'].includes(location.pathname);
  const knownPath=location.pathname==='/'||authPath||['/dashboard','/favorites','/collections','/search','/notifications','/contact','/planner','/welcome'].includes(location.pathname)||location.pathname.startsWith('/profile/')||location.pathname==='/atlas'||location.pathname.startsWith('/atlas/')||location.pathname.startsWith('/photo/')||location.pathname==='/admin/inquiries';
  if (!knownPath) return <><a className="skip-link" href="#main-content">Skip to main content</a><main id="main-content" className="member-content"><p className="eyebrow">AERIS / 404</p><h1>This page drifted away.</h1><p className="member-lede">The address may have changed or the page may no longer be here.</p><Link to="/">Return to AERIS home →</Link></main></>;
  if (location.pathname==='/'&&!authPath) return <>{children}<aside className="account-launch"><Link to={profile? '/dashboard':'/login'}>{profile? profile.name:'Member sign in'} <UserRound size={15} /></Link></aside></>;
  const logout=() => { void (async () => { if (isSupabaseConfigured) await signOutSupabase(); else signOutMember(); setProfile(null); navigate('/'); })(); };
  return <div className="member-shell" data-theme={profile?.theme??'dark'} data-member-revision={revision}><header className="member-top"><Link to="/"><ArrowLeft size={15} /> Back to AERIS</Link><Link to="/"><span>A E R I S</span><small>Moments Above.</small></Link><nav><Link to="/dashboard">Journal</Link><Link to="/favorites">Favorites</Link><Link to="/collections">Collections</Link><Link to="/search">Search</Link><Link to="/atlas">Cloud Atlas</Link><Link to="/planner">Planner</Link><Link to="/contact">Contact</Link>{profile&&<button onClick={logout} aria-label="Sign out"><LogOut size={16} /></button>}</nav></header><a className="skip-link" href="#main-content">Skip to main content</a>{syncError&&<div className="member-sync-error" role="alert"><span>Some changes could not sync: {syncError}</span><button onClick={() => setSyncError('')} aria-label="Dismiss sync error">×</button></div>}
    {authPath? <AuthScreen path={location.pathname} onSuccess={(nextProfile) => { setProfile(nextProfile??currentProfile()); setAuthReady(true); const pending=localStorage.getItem('aeris:onboarding-pending'); if(location.pathname==='/register'||(pending&&pending===nextProfile?.email)){ localStorage.removeItem('aeris:onboarding-pending'); navigate('/welcome'); } else goAfterAuth(); }} />:location.pathname==='/contact'||location.pathname==='/search'||location.pathname==='/planner'||location.pathname==='/atlas'||location.pathname.startsWith('/atlas/')||location.pathname.startsWith('/photo/')||(location.pathname.startsWith('/profile/')&&location.pathname!=='/profile/me')? <MemberPage key={route} route={route} profile={profile??{ email: '', name: 'Guest', username: 'guest', joinedAt: new Date().toISOString(), verified: false, following: [], notifications: false, theme: 'dark', privacy: 'private' }} data={data} refresh={() => setRevision((v) => v+1)} />:<Protected profile={profile} ready={authReady}><MemberPage key={route} route={route} profile={profile!} data={data} refresh={() => setRevision((v) => v+1)} /></Protected>}
  </div>;
}

function AuthScreen({ path, onSuccess }: { path: string; onSuccess: (profile?: MemberProfile|null) => void; }) {
  const [message, setMessage]=useState(''); const [error, setError]=useState('');
  const [busy, setBusy]=useState(false);
  const submit=async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setError(''); setMessage(''); const form=new FormData(event.currentTarget); const email=String(form.get('email')??''); setBusy(true); try {
      if (path==='/register') {
        const name=String(form.get('name')??''); const password=String(form.get('password')??'');
        if (password.length<8) throw new Error('Use at least 8 characters for your password.');
        if (isSupabaseConfigured) { const result=await signUpWithSupabase(name, email, password); if (result.authenticated) onSuccess(await loadSupabaseProfile()); else { localStorage.setItem('aeris:onboarding-pending', result.email.toLowerCase()); setMessage(`Check ${result.email} for the verification link to finish creating your AERIS account.`); } }
        else { const created=await registerMember(name, email, password); onSuccess(created); }
      }
      else if (path==='/login') { const signedIn=isSupabaseConfigured? await signInWithSupabase(email, String(form.get('password')??'')):await signInMember(email, String(form.get('password')??'')); onSuccess(signedIn); }
      else if (path==='/forgot-password') { if (isSupabaseConfigured) { await requestSupabasePasswordReset(email); setMessage('If an account exists for that address, a password reset link is on its way.'); } else { setMessage('Demo mode — password reset email is not sent. Add Supabase Auth to enable account recovery.'); } }
      else if (path==='/verify-email') { if (isSupabaseConfigured) { const verifiedProfile=await loadSupabaseProfile(); if (!verifiedProfile?.verified) throw new Error('Open the verification link sent to your email, then return here.'); onSuccess(verifiedProfile); } else { setMessage('Demo mode — email verification is not available. Add Supabase Auth to verify email addresses.'); } }
      else if (path==='/reset-password') { if (!isSupabaseConfigured) throw new Error('Demo mode — password reset is unavailable because no reset email can be sent.'); const password=String(form.get('password')??''); if (password.length<8) throw new Error('Use at least 8 characters for your password.'); await updateSupabasePassword(password); setMessage('Password updated. You can now sign in.'); }
    } catch (e) { setError(e instanceof Error? e.message:'Something went wrong.'); } finally { setBusy(false); }
  };
  const title=path==='/register'? 'Create your journal':path==='/forgot-password'? 'Find your way back':path==='/verify-email'? 'Verify your email':path==='/reset-password'? 'Choose a new password':'Welcome back';
  return <main id="main-content" className="auth-stage"><section className="auth-card"><p className="eyebrow">A sky journal and shooting companion</p><h1>{title}</h1><p>Look closer. Learn the light. Plan your next photograph.</p><form onSubmit={submit}>{path==='/register'&&<label>Your name<input name="name" autoComplete="name" required /></label>}{path!=='/verify-email'&&!(isSupabaseConfigured&&path==='/reset-password')&&<label>Email address<input name="email" type="email" autoComplete="email" required /></label>}{(path==='/register'||path==='/login'||(path==='/reset-password'&&isSupabaseConfigured))&&<label>Password<input name="password" type="password" autoComplete={path==='/login'? 'current-password':'new-password'} minLength={8} required /></label>}<button className="member-primary" type="submit" disabled={busy}>{busy? 'Please wait…':path==='/register'? 'Create account':path==='/login'? 'Sign in':path==='/forgot-password'? isSupabaseConfigured? 'Email reset link':'Show recovery options':path==='/verify-email'? 'Check verification':'Reset password'}</button></form>{error&&<p className="member-error" role="alert">{error}</p>}{message&&<p className="member-success" role="status">{message}</p>}<div className="auth-links">{path!=='/login'&&<Link to="/login">Sign in</Link>}{path!=='/register'&&<Link to="/register">Create account</Link>}{path==='/login'&&<Link to="/forgot-password">Forgot password?</Link>}</div><small className="demo-note">{isSupabaseConfigured? 'AERIS uses Supabase Auth for email verification and password recovery.':'Demo mode — profiles and saved items stay in this browser. Password recovery and email verification require Supabase Auth.'}</small></section></main>;
}

function SearchFilters({ cloud, setCloud, time, setTime, season, setSeason, mood, setMood, place, setPlace }: { cloud:string; setCloud:(value:string)=>void; time:string; setTime:(value:string)=>void; season:string; setSeason:(value:string)=>void; mood:string; setMood:(value:string)=>void; place:string; setPlace:(value:string)=>void; }) {
  const cloudTypes=[...new Set(photographs.map((photo)=>photo.cloudType))];
  const locations=[...new Set(photographs.map((photo)=>photo.location))];
  const clearAll=()=>{setCloud('all');setTime('all');setSeason('all');setMood('all');setPlace('all');};
  const active=[['Cloud',cloud,setCloud],['Time',time,setTime],['Season',season,setSeason],['Mood',mood,setMood],['Location',place,setPlace]] as const;
  return <><div className="member-search-filters"><label>Cloud type<select value={cloud} onChange={(event)=>setCloud(event.target.value)}><option value="all">All clouds</option>{cloudTypes.map((value)=><option key={value} value={value}>{value}</option>)}</select></label><label>Time of day<select value={time} onChange={(event)=>setTime(event.target.value)}><option value="all">Any light</option>{['dawn','morning','day','golden-hour','dusk'].map((value)=><option key={value} value={value}>{value.replace('-', ' ')}</option>)}</select></label><label>Season<select value={season} onChange={(event)=>setSeason(event.target.value)}><option value="all">All seasons</option>{['spring','summer','autumn','winter'].map((value)=><option key={value} value={value}>{value}</option>)}</select></label><label>Mood / color<select value={mood} onChange={(event)=>setMood(event.target.value)}><option value="all">Any mood</option>{['soft','cool','warm','dramatic','green','open'].map((value)=><option key={value} value={value}>{value}</option>)}</select></label><label>Location<select value={place} onChange={(event)=>setPlace(event.target.value)}><option value="all">All locations</option>{locations.map((value)=><option key={value} value={value}>{value}</option>)}</select></label></div>{active.some(([,value])=>value!=='all')&&<div className="member-filter-chips" aria-label="Active filters">{active.filter(([,value])=>value!=='all').map(([label,value,setter])=><button type="button" key={label} onClick={()=>setter('all')}>{label}: {value} ×</button>)}<button type="button" onClick={clearAll}>Clear filters</button></div>}</>;
}

function MemberPage({ route, profile, data, refresh }: { route: string; profile: MemberProfile; data: ReturnType<typeof memberData>; refresh: () => void; }) {
  const [query, setQuery]=useState(() => new URLSearchParams(location.search).get('q') ?? ''); const [debouncedQuery, setDebouncedQuery]=useState(query);
  const [cloudFilter, setCloudFilter]=useState(() => new URLSearchParams(location.search).get('cloud') ?? 'all');
  const [timeFilter, setTimeFilter]=useState(() => new URLSearchParams(location.search).get('time') ?? 'all');
  const [seasonFilter, setSeasonFilter]=useState(() => new URLSearchParams(location.search).get('season') ?? 'all');
  const [moodFilter, setMoodFilter]=useState(() => new URLSearchParams(location.search).get('mood') ?? 'all');
  const [placeFilter, setPlaceFilter]=useState(() => new URLSearchParams(location.search).get('place') ?? 'all');
  useEffect(() => { const timer=window.setTimeout(() => setDebouncedQuery(query), 250); return () => window.clearTimeout(timer); }, [query]);
  const photos=useMemo(() => photographs.filter((photo) => data.favorites.includes(photo.id)), [data.favorites]);
  const searchResults=useMemo(() => { const q=debouncedQuery.trim().toLowerCase(); return photographs.filter((photo) => { const facet=galleryFacets[photo.id]; const matchesQuery=!q||`${photo.title} ${photo.category} ${photo.location} ${photo.description}`.toLowerCase().includes(q); return matchesQuery&&(cloudFilter==='all'||photo.cloudType===cloudFilter)&&(timeFilter==='all'||facet?.timeOfDay===timeFilter)&&(seasonFilter==='all'||facet?.season===seasonFilter)&&(moodFilter==='all'||facet?.mood===moodFilter)&&(placeFilter==='all'||photo.location===placeFilter); }); }, [cloudFilter, debouncedQuery, moodFilter, placeFilter, seasonFilter, timeFilter]);
  const collectionResults=useMemo(() => { const q=debouncedQuery.trim().toLowerCase(); return q? data.collections.filter((collection) => collection.name.toLowerCase().includes(q)):[]; }, [data.collections, debouncedQuery]);
  const userResults=useMemo(() => findLocalProfiles(debouncedQuery), [debouncedQuery]);
  const section=route.split('?')[0];
  useEffect(() => {
    if (section !== '/search') return;
    const url = new URL(location.href);
    const values: Array<[string,string]> = [['q',debouncedQuery.trim()],['cloud',cloudFilter],['time',timeFilter],['season',seasonFilter],['mood',moodFilter],['place',placeFilter]];
    for (const [key,value] of values) { if (value&&value!=='all') url.searchParams.set(key,value); else url.searchParams.delete(key); }
    history.replaceState(history.state, '', `${url.pathname}${url.search}${url.hash}`);
  }, [cloudFilter, debouncedQuery, moodFilter, placeFilter, seasonFilter, section, timeFilter]);
  const viewedProfile=section.startsWith('/profile/')? (section==='/profile/me'? profile:findLocalProfileByUsername(decodeURIComponent(section.slice('/profile/'.length)))):null;
  const isOwnProfile=Boolean(viewedProfile&&viewedProfile.email===profile.email);
  const profileData=viewedProfile? memberData(viewedProfile.email):data;
  const toggle=(photo: Photograph) => { toggleFavorite(photo.id); refresh(); };
  const create=() => { const name=prompt('Name this collection'); if (name?.trim()) { addCollection(name); addNotice(`Collection created: ${name.trim()}`); refresh(); } };
  const profileLabel=viewedProfile?.name??(section.startsWith('/profile/')? `@${decodeURIComponent(section.slice('/profile/'.length))}`:profile.name);
  const title=section==='/welcome'? 'Welcome to AERIS':section.startsWith('/atlas')? 'Cloud Atlas':section.startsWith('/photo/')? 'Photograph details':section==='/admin/inquiries'? 'Inquiry inbox':section==='/planner'? 'Shoot Planner':section==='/favorites'? 'Saved photographs':section==='/collections'? 'Your collections':section==='/search'? 'Find a moment':section==='/contact'? 'Start a conversation':section==='/notifications'? 'Notifications':section.startsWith('/profile/')? profileLabel:'Your journal';
  return <main id="main-content" className="member-content"><p className="eyebrow">AERIS / MEMBER JOURNAL</p><h1>{title}</h1>
    {section==='/dashboard'&&<><div className="member-grid"><section className="member-panel"><div className="member-avatar" aria-label={`${profile.name} profile image`}>{profile.name.slice(0, 1).toUpperCase()}</div><h2>{profile.name}</h2><p>{profile.email}</p><small>Member since {new Date(profile.joinedAt).toLocaleDateString()}</small><Link to="/profile/me">View profile</Link></section><section className="member-panel"><Heart /><h2>Your activity</h2><p>{data.viewed.length} photos viewed · {data.collections.length} collections · {data.favorites.length} favorites</p><Link to="/favorites">Explore your saved photographs →</Link></section><section className="member-panel"><Bell /><h2>Notifications</h2><Link to="/notifications">View notification center →</Link><label className="member-check"><input type="checkbox" checked={profile.notifications} onChange={(e) => { updateProfile({ notifications: e.target.checked }); refresh(); }} /> Receive journal updates</label>{data.notices.slice(0, 2).map((item) => <p key={item}>{item}</p>)}</section><section className="member-panel"><h2>Preferences</h2><label>Theme <select value={profile.theme} onChange={(e) => { updateProfile({ theme: e.target.value as 'dark'|'light' }); refresh(); }}><option value="dark">Dark</option><option value="light">Light</option></select></label><label>Profile visibility <select value={profile.privacy} onChange={(e) => { updateProfile({ privacy: e.target.value as 'private'|'public' }); refresh(); }}><option value="private">Private</option><option value="public">Public</option></select></label></section></div><div className="member-toolbar"><h2>Recently viewed</h2><Link to="/search">Discover more →</Link></div><div className="member-gallery">{data.viewed.map((id) => { const photo=photographs.find((p) => p.id===id); return photo? <PhotoTile key={id} photo={photo} />:null; })}</div><div className="member-toolbar"><h2>Recommended for you</h2><Link to="/favorites">Based on your saved moments →</Link></div><div className="member-gallery">{photographs.filter((photo) => !data.favorites.includes(photo.id)&&(!data.favorites.length||photographs.find((item) => item.id===data.favorites[0])?.category===photo.category)).slice(0, 3).map((photo) => <PhotoTile key={photo.id} photo={photo} action={<button onClick={() => toggle(photo)}><Heart size={15} /> Save</button>} />)}</div></>}
    {section.startsWith('/atlas')&&<Suspense fallback={<p role="status">Opening the Cloud Atlas…</p>}><CloudAtlasPage pathname={section} /></Suspense>}
    {section==='/planner'&&<Suspense fallback={<p role="status">Calculating today’s light…</p>}><PlannerPage profile={profile.email ? profile : null} /></Suspense>}
    {section.startsWith('/photo/')&&<Suspense fallback={<p role="status">Opening photograph…</p>}><PhotoDetailPage photo={photographs.find((photo) => photo.id===decodeURIComponent(section.slice('/photo/'.length)))??null} /></Suspense>}
    {section==='/admin/inquiries'&&<Suspense fallback={<p role="status">Loading the inquiry inbox…</p>}><InquiryInbox profile={profile} /></Suspense>}
    {section==='/welcome'&&<Suspense fallback={<p role="status">Preparing your journal…</p>}><OnboardingPage profile={profile} onComplete={() => navigate('/dashboard')} /></Suspense>}
    {section==='/favorites'&&<><p className="member-lede">{photos.length} photographs held close.</p>{photos.length? <div className="member-gallery">{photos.map((photo) => <PhotoTile key={photo.id} photo={photo} action={<button onClick={() => toggle(photo)} aria-label={`Remove ${photo.title} from favorites`}><Heart fill="currentColor" size={16} /> Saved</button>} />)}</div>:<div className="member-empty"><Heart /><h2>A little space for what you love.</h2><p>Save a photograph from the gallery and it will be waiting here.</p><Link to="/#collection">Visit the collection →</Link></div>}</>}
    {section==='/collections'&&<><div className="member-toolbar"><p className="member-lede">Personal albums, gathered in one place.</p><button className="member-primary" onClick={create}><Plus size={16} /> New collection</button></div>{data.collections.length? <div className="member-grid">{data.collections.map((collection) => <section className="member-panel" key={collection.id}><h2>{collection.name}</h2><p>{collection.photoIds.length} photographs · {collection.isPublic? 'Public':'Private'}</p><button className="member-delete" onClick={() => { const name=prompt('Rename collection', collection.name); if (name?.trim()) { updateCollection(collection.id, { name: name.trim() }); refresh(); } }}>Rename collection</button><label>Add a saved photograph <select defaultValue="" onChange={(e) => { if (!e.target.value) return; updateCollection(collection.id, { photoIds: [...new Set([...collection.photoIds, e.target.value])] }); refresh(); }}><option value="">Choose photo</option>{photos.map((photo) => <option key={photo.id} value={photo.id}>{photo.title}</option>)}</select></label><ul>{collection.photoIds.map((id) => <li key={id}>{photographs.find((p) => p.id===id)?.title??id} <button onClick={() => { updateCollection(collection.id, { photoIds: collection.photoIds.filter((item) => item!==id) }); refresh(); }}>Remove</button></li>)}</ul><label><input type="checkbox" checked={collection.isPublic} onChange={(e) => { updateCollection(collection.id, { isPublic: e.target.checked }); refresh(); }} /> Make public</label><button className="member-delete" onClick={() => { deleteCollection(collection.id); refresh(); }}><Trash2 size={14} /> Delete collection</button></section>)}</div>:<div className="member-empty"><h2>Give your photographs a place.</h2><button className="member-primary" onClick={create}>Create your first collection</button></div>}</>}
    {section==='/search'&&<><label className="member-search"><Search /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Try ‘clouds’, ‘Norway’ or ‘first light’" autoFocus /></label><SearchFilters cloud={cloudFilter} setCloud={setCloudFilter} time={timeFilter} setTime={setTimeFilter} season={seasonFilter} setSeason={setSeasonFilter} mood={moodFilter} setMood={setMoodFilter} place={placeFilter} setPlace={setPlaceFilter} />{collectionResults.length>0&&<div className="member-search-collections"><h2>Collections</h2>{collectionResults.map((collection) => <Link key={collection.id} to="/collections"><Highlight text={collection.name} query={debouncedQuery} /> <small>{collection.photoIds.length} photographs</small></Link>)}</div>}{userResults.length>0&&<div className="member-search-collections"><h2>Photographers</h2>{userResults.map((user) => <Link key={user.email} to={`/profile/${user.username}`}><Highlight text={user.name} query={debouncedQuery} /> <small>@{user.username}</small></Link>)}</div>}<div className="member-gallery">{searchResults.map((photo) => <PhotoTile key={photo.id} photo={photo} query={debouncedQuery} action={<button onClick={() => toggle(photo)} aria-pressed={isFavorite(photo.id)}><Heart size={16} fill={isFavorite(photo.id)? 'currentColor':'none'} /> {isFavorite(photo.id)? 'Saved':'Save'}</button>} />)}</div>{(query||cloudFilter!=='all'||timeFilter!=='all'||seasonFilter!=='all'||moodFilter!=='all'||placeFilter!=='all')&&searchResults.length===0&&collectionResults.length===0&&userResults.length===0&&<p className="member-empty">No photographs, collections, or people found. Remove a filter or try another term.</p>}</>}
    {section.startsWith('/profile/')&&(!viewedProfile||(!isOwnProfile&&viewedProfile.privacy==='private'))&&<div className="member-empty"><UserRound /><h2>This photographer’s journal is private.</h2><p>Only public AERIS profiles can be viewed here.</p></div>}
    {section.startsWith('/profile/')&&viewedProfile&&(isOwnProfile||viewedProfile.privacy==='public')&&<><div className="member-panel"><UserRound /><h2>{profileLabel}</h2><p>{viewedProfile.email}</p><p>{localFollowerCount(viewedProfile.username)} followers · Member since {new Date(viewedProfile.joinedAt).toLocaleDateString()}</p>{!isOwnProfile&&<button className="member-primary" onClick={() => { if (!profile.email) { navigate(`/login?next=${encodeURIComponent(`/profile/${viewedProfile.username}`)}`); return; } const following=profile.following.includes(viewedProfile.username)? profile.following.filter((name) => name!==viewedProfile.username):[...profile.following, viewedProfile.username]; updateProfile({ following }); addNotice(following.includes(viewedProfile.username)? `You are now following ${viewedProfile.name}.`:`You unfollowed ${viewedProfile.name}.`); refresh(); }}>{profile.following.includes(viewedProfile.username)? 'Following':'Follow photographer'}</button>}</div><div className="member-grid">{profileData.collections.filter((collection) => collection.isPublic).map((collection) => <section className="member-panel" key={collection.id}><h2>{collection.name}</h2><p>{collection.photoIds.length} photographs</p>{collection.photoIds.map((id) => photographs.find((photo) => photo.id===id)).filter((photo): photo is Photograph => Boolean(photo)).map((photo) => <p key={photo.id}>{photo.title} · {photo.category}</p>)}</section>)}</div></>}
    {section==='/contact'&&<ContactForm />}
    {section==='/notifications'&&<div className="member-panel"><h2>Your notification center</h2>{data.notices.length? data.notices.map((item, index) => <p key={`${item}-${index}`}>{item}</p>):<p>Your journal is quiet for now.</p>}</div>}
    <footer className="member-foot"><Link to="/contact">Inquiries</Link><span>Crafted for moments above.</span><Link to="/dashboard">Privacy & settings</Link>{profile.role === 'admin'&&<Link to="/admin/inquiries">Admin inbox</Link>}</footer>
  </main>;
}
